on:
  release:
    types: [created]

permissions:
    contents: write
    packages: write

jobs:
  binary-builds:
    name: Build Banaries
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos:
          - linux
          - freebsd
          - windows
        goarch:
          - amd64
          - arm
          - arm64
          - "386"
    steps:
    - uses: actions/checkout@v4
    - uses: wangyoucao577/go-release-action@v1
      name: Build ${{ matrix.goos }}/${{ matrix.goarch }}
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
